### PR TITLE
Add FIPS build.

### PR DESCRIPTION
**Pull request by joshdrake**
This PR adds a new Dockerfile using an Alpine base with OpenSSL compiled in FIPS-mode and a binary built with `boringcrypto`.

💔Thank you!

### CODE REVIEW

**Comment by hslatman** [comment]
Probably fails on the file fixed in https://github.com/smallstep/step-kms-plugin/pull/118/commits/4bdb0d2e92264b4488d9faa30a0a76a5db18e132.

**Review by maraino — CHANGES_REQUESTED** [review]
Although this looks ok, there are a couple of issues:

- What is the purpose of this build? Because if we want to support PKCS#11, the support of drivers using musl is very limited. A Debian build makes more sense.
- If the supported cloud kms drivers are using TLS, and they will this build will not be limited to the FIPS supported crypto.

**Comment by maraino** [comment]
See https://github.com/smallstep/cli/pull/1076#pullrequestreview-1763148191

**Comment by maraino** [comment]
Closed in favor of #120

**Pull request closed without merging**
